# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Scholar's Weekly
site_description: 不换写周刊的地方～
site_url: https://weekly.binlin.wang
# Repository
repo_name: bigbigDreamer/weekly
repo_url: https://github.com/bigbigDreamer/weekly
edit_uri: ""

use_directory_urls: true
docs_dir: .
extra:
  homepage: https://weekly.binlin.wang
  analytics:
#    provider: google
#    property: G-XJPLDWZN92
    feedback:
      title: 您觉得周刊怎么样？
      ratings:
        - icon: material/emoticon-happy-outline
          name: 非常棒！666！！！
          data: 1
          note: >-
            谢谢你的鼓励，我会继续坚持写作的!
        - icon: material/emoticon-sad-outline
          name: 小编还需要再接再厉！
          data: 0
          note: >-
            感谢反馈，我会继续努力进步的！
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bigbigDreamer
      name: Follow Me In GitHub
    - icon: bootstrap/mask
      link: https://montage.binlin.wang
      name: montageJs
    - icon: fontawesome/solid/paper-plane
      link: mailto:<jadeface.scholar@gmail.com>

copyright: Copyright &copy; 2022-2023  Scholar(不换)

theme:
  favicon: images/favicon.png
  custom_dir: overrides
  logo: images/logo.svg
  name: material
  language: zh
  features:
    - content.code.annotate
    # - content.tabs.link
#    - header.autohide
#    - navigation.expand
    #- navigation.indexes
#    - navigation.instant 暂时先不开启，，，发现 psa 内切换路由不会重新更新资源...
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material//weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to light mode
markdown_extensions:
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - same-dir
  - search
  - minify:
      minify_html: true
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: iso_datetime
      timezone: Asia/Brunei



nav:
  - 介绍: README.md
  - 周刊:
      - 2022: # 2022:
         - 七月:
             - 第1期: ./docs/2022/07/01/index.md
             - 第2期: ./docs/2022/07/02/index.md
         - 八月:
             - 第3期: ./docs/2022/08/03/index.md
             - 第4期: ./docs/2022/08/04/index.md
             - 第5期: ./docs/2022/08/05/index.md
             - 第6期: ./docs/2022/08/06/index.md
         - 九月:
             - 第7期: ./docs/2022/09/07/index.md
         - 十月:
             - 第8期: ./docs/2022/10/08/index.md
      - 2023: #2023:
         - 二月:
             - 第9期: ./docs/2023/02/09/index.md
             - 第10期: ./docs/2023/02/10/index.md
             - 第11期: ./docs/2023/02/11/index.md
             - 第12期: ./docs/2023/02/12/index.md
         - 三月:
             - 第13期: ./docs/2023/03/13/index.md
             - 第14期: ./docs/2023/03/14/index.md
             - 第15期: ./docs/2023/03/15/index.md
             - 第16期: ./docs/2023/03/16/index.md
         - 四月:
             - 第17期: ./docs/2023/04/17/index.md
             - 第18期: ./docs/2023/04/18/index.md
             - 第19期: ./docs/2023/04/19/index.md
         - 五月:
             - 第20期: ./docs/2023/05/20/index.md
             - 第21期: ./docs/2023/05/21/index.md
             - 第22期: ./docs/2023/05/22/index.md
             - 第23期: ./docs/2023/05/23/index.md
         - 六月:
             - 第24期: ./docs/2023/06/24/index.md
             - 第25期: ./docs/2023/06/25/index.md
             - 第26期: ./docs/2023/06/26/index.md
             - 第27期: ./docs/2023/06/27/index.md
         - 七月:
             - 第28期: ./docs/2023/07/28/index.md
         - 八月:
             - 第29期: ./docs/2023/08/29/index.md
         - 九月:
             - 第30期: ./docs/2023/09/30/index.md
      - 2024: #2023:
          - 一月:
             -  第31期: ./docs/2024/01/31/index.md
             -  第32期: ./docs/2024/01/32/index.md
             -  第33期: ./docs/2024/01/33/index.md
             -  第34期: ./docs/2024/01/34/index.md
  - 声明: ./DECLARATION.md
  - 里程碑: ./LANDMARK.md



