name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Rebuild-everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 将仓库内master分支的内容下载到工作目录
        uses: actions/checkout@v3 # 脚本来自 https://github.com/actions/checkout
        with:
          ref: main
      - name: Install packages
      - run: pip install -r .requirements.txt
      - run: mkdocs build --strict
      - name: Generate CNAME File
      - run: echo weekly.bigdreamer.cc > CNAME
      - run: mkdir docs && echo weekly.bigdreamer.cc > docs/CNAME
      - uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_DOMAIN: weekly.bigdreamer.cc
          CONFIG_FILE: mkdocs.yml
          REQUIREMENTS: .requirements.txt
