name: Email Workflow
on:
  workflow_dispatch:
    inputs:
      emailSubject:
        description: Email Subject
        default: Scholar's Weekly 第 1 期
        required: true
      htmlBody:
        description: Html Body
        default: https://weekly.bigdreamer.cc
        required: true
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - run: curl -o email.html ${{ github.event.inputs.htmlBody }}
      - run: echo file://email.html
      - run: cat file://email.html
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: ${{ github.event.inputs.emailSubject }}
          html_body: |
            <div><p>Hi, Scholar's Weekly Updated! Please click <a href="${{ github.event.inputs.htmlBody }}">link</a></p></div>
          to: jadeface.scholar@gmail.com
          from: Scholar's Weekly
          content_type: text/html
